apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-deploy
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/config
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: homepage-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: homepage-service
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
spec:
  rules:
  - host: home.local  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage-service 
            port:
              number: 80