---
# 1. El Deployment: Define QUÉ queremos correr (la "Receta")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2  # <--- MAGIA: Queremos 2 copias idénticas siempre
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
# 2. El Service: Define CÓMO entramos (la "Puerta")
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080      # Puerto externo (donde tú llamarás)
      targetPort: 80  # Puerto interno del contenedor
  type: LoadBalancer  # K3s tiene un "truco" para que esto funcione en local